name: Docker Build Verification

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: test-build:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Verify image
      run: |
        docker image ls
        echo "✅ Docker image built successfully" 